# /Users/sridhar/Dev/rat-risk-inspector/rri_transformation/models/schema.yml
version: 2

models:
  - name: clean_restaurant_inspection
    description: "Cleaned restaurant inspection data with business logic applied"
    columns:
      - name: camis
        description: "Restaurant identifier"
        tests:
          - not_null
      - name: inspection_date
        description: "Date of inspection"
        tests:
          - not_null
      - name: score
        description: "Inspection score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: boro
        description: "Borough code"
        tests:
          - not_null
          - accepted_values:
              values: ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']
      - name: bin
        description: "Building identifier"
        tests:
          - not_null
      - name: zipcode
        description: "ZIP code"
        tests:
          - not_null

  - name: clean_rat_inspection
    description: "Cleaned rat inspection data with business logic applied"
    columns:
      - name: bin
        description: "Building identifier"
        tests:
          - not_null
      - name: inspection_date
        description: "Date of inspection"
        tests:
          - not_null
      - name: result
        description: "Inspection result"
        tests:
          - not_null
          - accepted_values:
              values: ['PASSED', 'FAILED', 'FAILED FOR OTHER R', 'RAT ACTIVITY']
      - name: inspection_type
        description: "Type of inspection"
        tests:
          - not_null
      - name: borough
        description: "Borough name"
        tests:
          - not_null
          - accepted_values:
              values: ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']
