# /Users/sridhar/Dev/rat-risk-inspector/rri_transformation/models/stage/schema.yml
version: 2

models:
  - name: stg_restaurant_inspection
    description: "Staged restaurant inspection data with computed scores and grades"
    columns:
      - name: camis
        description: "Restaurant identifier"
        tests:
          - not_null
      - name: inspection_date
        description: "Date of inspection"
        tests:
          - not_null
      - name: computed_score
        description: "Computed inspection score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: computed_grade
        description: "Computed restaurant grade"
        tests:
          - not_null
          - accepted_values:
              values: ['A', 'B', 'C', 'N']
      - name: boro
        description: "Borough code"
        tests:
          - not_null
          - accepted_values:
              values: ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']
      - name: bin
        description: "Building identifier"
        tests:
          - not_null
      - name: zipcode
        description: "ZIP code"
        tests:
          - not_null
      - name: violation_code
        description: "Violation code"
        tests:
          - not_null

  - name: stg_rat_inspection
    description: "Staged rat inspection data with geocoding applied"
    columns:
      - name: bin
        description: "Building identifier"
        tests:
          - not_null
      - name: inspection_date
        description: "Date of inspection"
        tests:
          - not_null
      - name: result
        description: "Inspection result"
        tests:
          - not_null
          - accepted_values:
              values: ['PASSED', 'FAILED', 'FAILED FOR OTHER R', 'RAT ACTIVITY']
      - name: inspection_type
        description: "Type of inspection"
        tests:
          - not_null
      - name: borough
        description: "Borough name"
        tests:
          - not_null
          - accepted_values:
              values: ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']